name:seafile
description:  seafile system
version: # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: zhuxiaowei
license: # The license
projectURL: # A URL related to the catalog entry
