db:
  image: mariadb:10.1
  container_name: seafile-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # Requested, set the root's password of MySQL service.
    - MYSQL_LOG_CONSOLE=true
  volumes:
    - ${DB_DATA_DIR}:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.

memcached:
  image: memcached:1.5.6
  container_name: seafile-memcached
  entrypoint: memcached -m 256
        
seafile:
  image: seafileltd/seafile-mc:latest
  container_name: seafile
  ports:
    - "${SEAFILE_PORT}:80"
    - "${SHARE_PORT}:8000"
#   - "443:443"  # If https is enabled, cancel the comment.
  volumes:
    - ${SEAFILE_VOLUME}:/shared   # Requested, specifies the path to Seafile data persistent store.
  environment:
    - DB_HOST=db
    - DB_ROOT_PASSWD=${DB_PASSWORD}  # Requested, the value shuold be root's password of MySQL service.
    - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
    - SEAFILE_ADMIN_EMAIL=${EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
    - SEAFILE_ADMIN_PASSWORD=${ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
    - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
#   - SEAFILE_SERVER_HOSTNAME=file.yechuan.org # Specifies your host name if https is enabled.
  links:
    - db:db
    - memcached:memcached
    - onlyoffice:onlyoffice

onlyoffice:
  image: onlyoffice/documentserver
  container_name: onlyoffice
  ports:
    - "${ONLYOFFICE_PORT}:80"
